'Gathering stats---------------------------------------------------------------------------------------
name_of_scripts = "ACTIONS - MAXIS MNSURE LOOKUP.vbs"
start_time = timer

BeginDialog mx_msr_dlg, 0, 0, 181, 360, "Search for Affiliated Case"
  EditBox 80, 85, 90, 15, int_case
  EditBox 80, 105, 90, 15, mnsure_id
  EditBox 80, 145, 90, 15, maxis_case_number
  EditBox 80, 165, 90, 15, recip_id
  EditBox 80, 205, 45, 15, first_name
  EditBox 125, 205, 45, 15, last_name
  EditBox 80, 225, 90, 15, ssn
  EditBox 15, 265, 150, 15, addr_line1
  EditBox 15, 285, 150, 15, addr_line2
  EditBox 15, 305, 70, 15, addr_city
  EditBox 90, 305, 20, 15, addr_state
  EditBox 115, 305, 50, 15, addr_zip
  ButtonGroup ButtonPressed
    OkButton 80, 340, 50, 15
    CancelButton 130, 340, 50, 15
  GroupBox 5, 75, 170, 50, "MNSure Case Information"
  GroupBox 5, 135, 170, 50, "MAXIS Case Information"
  GroupBox 5, 195, 170, 50, "Client Information"
  GroupBox 5, 250, 170, 80, "Address"
  Text 15, 90, 60, 10, "Integrated Case #"
  Text 15, 110, 65, 10, "MNSure ID"
  Text 15, 150, 60, 10, "MAXIS Case #"
  Text 15, 170, 65, 10, "Recipient ID"
  Text 15, 210, 65, 10, "Name (First Last)"
  Text 15, 230, 65, 10, "SSN"
  Text 10, 10, 160, 45, "Please enter your search criteria below. The script will check your search criteria against a report generated by the state to determine if you have a case or client open in both MAXIS and MNSure."
EndDialog

DIALOG mx_msr_dlg
	IF ButtonPressed = 0 THEN stopscript

'Opening the Excel file
Set objExcel = CreateObject("Excel.Application")
objExcel.Visible = false
Set objWorkbook = objExcel.Workbooks.Open("Q:\Blue Zone Scripts\Spreadsheets for script use\maxis mnsure cases.xlsx", ReadOnly=True) 
objExcel.DisplayAlerts = false

Set objReport = CreateObject("Excel.Application")
objReport.Visible = True
Set objOutput = objReport.Workbooks.Add()
objReport.DisplayAlerts = True
objReport.Range("A1:O8500").Value = objExcel.Range("A1:O8500").Value

objExcel.Worksheets("Sheet2").Activate
objExcel.Quit

'When migrating data from the original Excel file to the spreadsheet used for this script, follow these steps...
'(1) Delete the following columns from the original report...
'		(a) Column A: ServiceLocation
'		(b) Column B: County of Residence
'		(c) Column I: Major Program
'		(d) Column J: (Program) Begin Date
'		(e) Column K: (Program) End Date
'		(f) Column M: Program (Code)
'		(g) Column N: (Program) Status
'		(h) Column P: Gender
'...the output should go by the following columns...
'(a) Integrated Case
'(b) Recipient ID
'(c) MNSure ID
'(d) First Name
'(e) MiddleInitial
'(f) Last Name
'(g) Maxis Case Number (filtered to remove blank cells)
'(h) Birth Date
'(i) Social Security Number
'(j) SMI
'(k) Address Line 1
'(l) Address Line 2
'(m) City
'(n) State
'(o) Zip

searchCriteria = ""
IF int_case <> "" THEN 
	objReport.Range("A1").AutoFilter 1, "=" & int_case, 7,, False
	searchCriteria = searchCriteria & "Integrated Case = " & int_case & ";"
END IF
IF recip_id <> "" THEN 
	objReport.Range("B1").AutoFilter 2, "=" & recip_id, 7,, False
	searchCriteria = searchCriteria & "Recipient ID = " & recip_id & ";"
END IF
IF mnsure_id <> "" THEN 
	objReport.Range("C1").AutoFilter 3, "=" & mnsure_id, 7,, False
	searchCriteria = searchCriteria & "MNSure ID = " & mnsure_id & ";"
END IF
IF first_name <> "" THEN 
	objReport.Range("D1").AutoFilter 4, "=" & UCASE(first_name), 7,, False
	searchCriteria = searchCriteria & "First Name = " & UCASE(first_name) & ";"
END IF
IF last_name <> "" THEN 
	objReport.Range("F1").AutoFilter 6, "=" & UCASE(last_name), 7,, False
	searchCriteria = searchCriteria & "Last Name = " & UCASE(last_name) & ";"
END IF
IF maxis_case_number <> "" THEN
	objReport.Range("G1").AutoFilter 7, "=" & maxis_case_number, 7,, False
	searchCriteria = searchCriteria & "MAXIS Case Number = " & maxis_case_number & ";"
END IF
IF ssn <> "" THEN 
	ssn = replace(ssn, "-", "")
	objReport.Range("I1").AutoFilter 9, "=" & ssn, 7,, False
	searchCriteria = searchCriteria & "SSN;"
END IF
IF addr_line1 <> "" THEN 
	objReport.Range("K1").AutoFilter 11, "=" & UCASE(addr_line1), 7,, False
	searchCriteria = searchCriteria & "Address = " & UCASE(addr_line1) & ";"
END IF
IF addr_line2 <> "" THEN 
	objReport.Range("L1").AutoFilter 12, "=" & UCASE(addr_line2), 7,, False
	searchCriteria = searchCriteria & "Address = " & UCASE(addr_line2) & ";"
END IF
IF addr_city <> "" THEN	
	objReport.Range("M1").AutoFilter 13, "=" & UCASE(addr_city), 7,, False
	searchCriteria = searchCriteria & "City = " & UCASE(addr_city) & ";"
END IF
IF addr_state <> "" THEN 
	objReport.Range("N1").AutoFilter 14, "=" & UCASE(addr_state), 7,, False
	searchCriteria = searchCriteria & "State = " & UCASE(addr_state) & ";"
END IF
IF addr_zip <> "" THEN 
	objReport.Range("O1").AutoFilter 15, "=" & addr_zip, 7,, False
	searchCriteria = searchCriteria & "ZIP = " & addr_zip & ";"
END IF

objReport.Caption = "Search Criteria: " & searchCriteria
objReport.Rows(1).RowHeight = 15

FOR i = 1 to 15
	objReport.Columns(i).AutoFit()
NEXT

search_display = replace(searchCriteria, ";", (";" & vbCr & vbTab))

MsgBox "Done!" & vbCr & vbCr & "The script is displaying the results of your search for cases and clients open in MAXIS and MNSure meeting the following criteria: " & vbCr & vbCr & vbTab & search_display

script_end_procedure("")
